# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
amplitudeh0.$(OBJEXTG): globals.$(OBJEXTG) diagramsl0.$(OBJEXTG) \
			diagramsl0.$(OBJEXTG)
p0_part21part21_part25part25_diagramsh0l0.mod: diagramsl0.$(OBJEXTG)
p0_part21part21_part25part25_d1h0l0.mod: d1h0l0.$(OBJEXTG)
p0_part21part21_part25part25_d2h0l0.mod: d2h0l0.$(OBJEXTG)
p0_part21part21_part25part25_amplitudeh0.mod: amplitudeh0.$(OBJEXTG)
p0_part21part21_part25part25_globalsh0.mod: globals.$(OBJEXTG)
