
OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
p9_part21part1_part1part25part25_matrix.$(OBJEXTG): matrix.$(OBJEXTG)
p10_partm1part21_partm1part25part25_matrix.$(OBJEXTG): matrix.$(OBJEXTG)
p11_part21partm1_partm1part25part25_matrix.$(OBJEXTG): matrix.$(OBJEXTG)
p12_part1partm1_part21part25part25_matrix.$(OBJEXTG): matrix.$(OBJEXTG)
p8_part1part21_part1part25part25_test.mod: test.$(OBJEXTG)
p8_part1part21_part1part25part25_matrix.mod: matrix.$(OBJEXTG)
p9_part21part1_part1part25part25_matrix.mod: p9_part21part1_part1part25part25_matrix.$(OBJEXTG)
p10_partm1part21_partm1part25part25_matrix.mod: p10_partm1part21_partm1part25part25_matrix.$(OBJEXTG)
p11_part21partm1_partm1part25part25_matrix.mod: p11_part21partm1_partm1part25part25_matrix.$(OBJEXTG)
p12_part1partm1_part21part25part25_matrix.mod: p12_part1partm1_part21part25part25_matrix.$(OBJEXTG)
test.$(OBJEXT): matrix.$(OBJEXT)
