
OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
p2_part21part21_part25part25part21_test.mod: test.$(OBJEXTG)
p2_part21part21_part25part25part21_matrix.mod: matrix.$(OBJEXTG)
test.$(OBJEXT): matrix.$(OBJEXT)
