# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
abbrevd2h0.$(OBJEXTG): globals.$(OBJEXTG)
d2h0l1.$(OBJEXTG): abbrevd2h0.$(OBJEXTG)
d2h0l1d.$(OBJEXTG): abbrevd2h0.$(OBJEXTG)
abbrevd7h0.$(OBJEXTG): globals.$(OBJEXTG)
d7h0l1.$(OBJEXTG): abbrevd7h0.$(OBJEXTG)
d7h0l1d.$(OBJEXTG): abbrevd7h0.$(OBJEXTG)
abbrevd9h0.$(OBJEXTG): globals.$(OBJEXTG)
d9h0l1.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l1d.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
abbrevd11h0.$(OBJEXTG): globals.$(OBJEXTG)
d11h0l1.$(OBJEXTG): abbrevd11h0.$(OBJEXTG)
d11h0l1d.$(OBJEXTG): abbrevd11h0.$(OBJEXTG)
abbrevd13h0.$(OBJEXTG): globals.$(OBJEXTG)
d13h0l1.$(OBJEXTG): abbrevd13h0.$(OBJEXTG)
d13h0l1d.$(OBJEXTG): abbrevd13h0.$(OBJEXTG)
golem95h0.$(OBJEXTG):  \
	d2h0l1.$(OBJEXTG) d2h0l1d.$(OBJEXTG) \
	d7h0l1.$(OBJEXTG) d7h0l1d.$(OBJEXTG) \
	d9h0l1.$(OBJEXTG) d9h0l1d.$(OBJEXTG) \
	d11h0l1.$(OBJEXTG) d11h0l1d.$(OBJEXTG) \
	d13h0l1.$(OBJEXTG) d13h0l1d.$(OBJEXTG)
ninjah0.$(OBJEXTG):  \
	d2h0l1.$(OBJEXTG) d2h0l131.$(OBJEXTG) d2h0l132.$(OBJEXTG) d2h0l121.$(OBJEXTG) \
	d7h0l1.$(OBJEXTG) d7h0l131.$(OBJEXTG) d7h0l132.$(OBJEXTG) d7h0l121.$(OBJEXTG) \
	d9h0l1.$(OBJEXTG) d9h0l131.$(OBJEXTG) d9h0l132.$(OBJEXTG) d9h0l121.$(OBJEXTG) \
	d11h0l1.$(OBJEXTG) d11h0l131.$(OBJEXTG) d11h0l132.$(OBJEXTG) d11h0l121.$(OBJEXTG) \
	d13h0l1.$(OBJEXTG) d13h0l131.$(OBJEXTG) d13h0l132.$(OBJEXTG) d13h0l121.$(OBJEXTG)
d2h0l131.$(OBJEXTG): abbrevd2h0.$(OBJEXTG)
d2h0l132.$(OBJEXTG): abbrevd2h0.$(OBJEXTG)
d2h0l121.$(OBJEXTG): abbrevd2h0.$(OBJEXTG)
d7h0l131.$(OBJEXTG): abbrevd7h0.$(OBJEXTG)
d7h0l132.$(OBJEXTG): abbrevd7h0.$(OBJEXTG)
d7h0l121.$(OBJEXTG): abbrevd7h0.$(OBJEXTG)
d9h0l131.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l132.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d9h0l121.$(OBJEXTG): abbrevd9h0.$(OBJEXTG)
d11h0l131.$(OBJEXTG): abbrevd11h0.$(OBJEXTG)
d11h0l132.$(OBJEXTG): abbrevd11h0.$(OBJEXTG)
d11h0l121.$(OBJEXTG): abbrevd11h0.$(OBJEXTG)
d13h0l131.$(OBJEXTG): abbrevd13h0.$(OBJEXTG)
d13h0l132.$(OBJEXTG): abbrevd13h0.$(OBJEXTG)
d13h0l121.$(OBJEXTG): abbrevd13h0.$(OBJEXTG)
amplitudeh0.$(OBJEXTG): globals.$(OBJEXTG) diagramsl0.$(OBJEXTG) golem95h0.$(OBJEXTG) ninjah0.$(OBJEXTG) \
			diagramsl0.$(OBJEXTG) \
			abbrevd2h0.$(OBJEXTG) \
			abbrevd7h0.$(OBJEXTG) \
			abbrevd9h0.$(OBJEXTG) \
			abbrevd11h0.$(OBJEXTG) \
			abbrevd13h0.$(OBJEXTG)
pb_part21part21_part25part25_diagramsh0l0.mod: diagramsl0.$(OBJEXTG)
pb_part21part21_part25part25_d1h0l0.mod: d1h0l0.$(OBJEXTG)
pb_part21part21_part25part25_d2h0l0.mod: d2h0l0.$(OBJEXTG)
pb_part21part21_part25part25_golem95h0.mod: golem95h0.$(OBJEXTG)
pb_part21part21_part25part25_ninjah0.mod: ninjah0.$(OBJEXTG) 
pb_part21part21_part25part25_d2h0l131.mod: d2h0l131.$(OBJEXTG)
pb_part21part21_part25part25_d2h0l132.mod: d2h0l132.$(OBJEXTG)
pb_part21part21_part25part25_d2h0l121.mod: d2h0l121.$(OBJEXTG)
pb_part21part21_part25part25_d7h0l131.mod: d7h0l131.$(OBJEXTG)
pb_part21part21_part25part25_d7h0l132.mod: d7h0l132.$(OBJEXTG)
pb_part21part21_part25part25_d7h0l121.mod: d7h0l121.$(OBJEXTG)
pb_part21part21_part25part25_d9h0l131.mod: d9h0l131.$(OBJEXTG)
pb_part21part21_part25part25_d9h0l132.mod: d9h0l132.$(OBJEXTG)
pb_part21part21_part25part25_d9h0l121.mod: d9h0l121.$(OBJEXTG)
pb_part21part21_part25part25_d11h0l131.mod: d11h0l131.$(OBJEXTG)
pb_part21part21_part25part25_d11h0l132.mod: d11h0l132.$(OBJEXTG)
pb_part21part21_part25part25_d11h0l121.mod: d11h0l121.$(OBJEXTG)
pb_part21part21_part25part25_d13h0l131.mod: d13h0l131.$(OBJEXTG)
pb_part21part21_part25part25_d13h0l132.mod: d13h0l132.$(OBJEXTG)
pb_part21part21_part25part25_d13h0l121.mod: d13h0l121.$(OBJEXTG)
pb_part21part21_part25part25_abbrevd2h0.mod: abbrevd2h0.$(OBJEXTG)
pb_part21part21_part25part25_d2h0l1.mod: d2h0l1.$(OBJEXTG)
pb_part21part21_part25part25_d2h0l1d.mod: d2h0l1d.$(OBJEXTG)
pb_part21part21_part25part25_abbrevd7h0.mod: abbrevd7h0.$(OBJEXTG)
pb_part21part21_part25part25_d7h0l1.mod: d7h0l1.$(OBJEXTG)
pb_part21part21_part25part25_d7h0l1d.mod: d7h0l1d.$(OBJEXTG)
pb_part21part21_part25part25_abbrevd9h0.mod: abbrevd9h0.$(OBJEXTG)
pb_part21part21_part25part25_d9h0l1.mod: d9h0l1.$(OBJEXTG)
pb_part21part21_part25part25_d9h0l1d.mod: d9h0l1d.$(OBJEXTG)
pb_part21part21_part25part25_abbrevd11h0.mod: abbrevd11h0.$(OBJEXTG)
pb_part21part21_part25part25_d11h0l1.mod: d11h0l1.$(OBJEXTG)
pb_part21part21_part25part25_d11h0l1d.mod: d11h0l1d.$(OBJEXTG)
pb_part21part21_part25part25_abbrevd13h0.mod: abbrevd13h0.$(OBJEXTG)
pb_part21part21_part25part25_d13h0l1.mod: d13h0l1.$(OBJEXTG)
pb_part21part21_part25part25_d13h0l1d.mod: d13h0l1d.$(OBJEXTG)
pb_part21part21_part25part25_amplitudeh0.mod: amplitudeh0.$(OBJEXTG)
pb_part21part21_part25part25_globalsh0.mod: globals.$(OBJEXTG)
