# vim: ts=3:sw=3

OBJEXT ?=o
OBJEXTG=$(OBJEXT)
# Module Dependencies:
abbrevd11h2.$(OBJEXTG): globals.$(OBJEXTG)
d11h2l1.$(OBJEXTG): abbrevd11h2.$(OBJEXTG)
d11h2l1d.$(OBJEXTG): abbrevd11h2.$(OBJEXTG)
abbrevd84h2.$(OBJEXTG): globals.$(OBJEXTG)
d84h2l1.$(OBJEXTG): abbrevd84h2.$(OBJEXTG)
d84h2l1d.$(OBJEXTG): abbrevd84h2.$(OBJEXTG)
abbrevd86h2.$(OBJEXTG): globals.$(OBJEXTG)
d86h2l1.$(OBJEXTG): abbrevd86h2.$(OBJEXTG)
d86h2l1d.$(OBJEXTG): abbrevd86h2.$(OBJEXTG)
abbrevd88h2.$(OBJEXTG): globals.$(OBJEXTG)
d88h2l1.$(OBJEXTG): abbrevd88h2.$(OBJEXTG)
d88h2l1d.$(OBJEXTG): abbrevd88h2.$(OBJEXTG)
golem95h2.$(OBJEXTG):  \
	d11h2l1.$(OBJEXTG) d11h2l1d.$(OBJEXTG) \
	d84h2l1.$(OBJEXTG) d84h2l1d.$(OBJEXTG) \
	d86h2l1.$(OBJEXTG) d86h2l1d.$(OBJEXTG) \
	d88h2l1.$(OBJEXTG) d88h2l1d.$(OBJEXTG)
ninjah2.$(OBJEXTG):  \
	d11h2l1.$(OBJEXTG) d11h2l131.$(OBJEXTG) d11h2l132.$(OBJEXTG) d11h2l121.$(OBJEXTG) \
	d84h2l1.$(OBJEXTG) d84h2l131.$(OBJEXTG) d84h2l132.$(OBJEXTG) d84h2l121.$(OBJEXTG) \
	d86h2l1.$(OBJEXTG) d86h2l131.$(OBJEXTG) d86h2l132.$(OBJEXTG) d86h2l121.$(OBJEXTG) \
	d88h2l1.$(OBJEXTG) d88h2l131.$(OBJEXTG) d88h2l132.$(OBJEXTG) d88h2l121.$(OBJEXTG)
d11h2l131.$(OBJEXTG): abbrevd11h2.$(OBJEXTG)
d11h2l132.$(OBJEXTG): abbrevd11h2.$(OBJEXTG)
d11h2l121.$(OBJEXTG): abbrevd11h2.$(OBJEXTG)
d84h2l131.$(OBJEXTG): abbrevd84h2.$(OBJEXTG)
d84h2l132.$(OBJEXTG): abbrevd84h2.$(OBJEXTG)
d84h2l121.$(OBJEXTG): abbrevd84h2.$(OBJEXTG)
d86h2l131.$(OBJEXTG): abbrevd86h2.$(OBJEXTG)
d86h2l132.$(OBJEXTG): abbrevd86h2.$(OBJEXTG)
d86h2l121.$(OBJEXTG): abbrevd86h2.$(OBJEXTG)
d88h2l131.$(OBJEXTG): abbrevd88h2.$(OBJEXTG)
d88h2l132.$(OBJEXTG): abbrevd88h2.$(OBJEXTG)
d88h2l121.$(OBJEXTG): abbrevd88h2.$(OBJEXTG)
amplitudeh2.$(OBJEXTG): globals.$(OBJEXTG) diagramsl0.$(OBJEXTG) golem95h2.$(OBJEXTG) ninjah2.$(OBJEXTG) \
			diagramsl0.$(OBJEXTG) \
			abbrevd11h2.$(OBJEXTG) \
			abbrevd84h2.$(OBJEXTG) \
			abbrevd86h2.$(OBJEXTG) \
			abbrevd88h2.$(OBJEXTG)
p8_part1part21_part1part25part25_diagramsh2l0.mod: diagramsl0.$(OBJEXTG)
p8_part1part21_part1part25part25_d1h2l0.mod: d1h2l0.$(OBJEXTG)
p8_part1part21_part1part25part25_d2h2l0.mod: d2h2l0.$(OBJEXTG)
p8_part1part21_part1part25part25_golem95h2.mod: golem95h2.$(OBJEXTG)
p8_part1part21_part1part25part25_ninjah2.mod: ninjah2.$(OBJEXTG) 
p8_part1part21_part1part25part25_d11h2l131.mod: d11h2l131.$(OBJEXTG)
p8_part1part21_part1part25part25_d11h2l132.mod: d11h2l132.$(OBJEXTG)
p8_part1part21_part1part25part25_d11h2l121.mod: d11h2l121.$(OBJEXTG)
p8_part1part21_part1part25part25_d84h2l131.mod: d84h2l131.$(OBJEXTG)
p8_part1part21_part1part25part25_d84h2l132.mod: d84h2l132.$(OBJEXTG)
p8_part1part21_part1part25part25_d84h2l121.mod: d84h2l121.$(OBJEXTG)
p8_part1part21_part1part25part25_d86h2l131.mod: d86h2l131.$(OBJEXTG)
p8_part1part21_part1part25part25_d86h2l132.mod: d86h2l132.$(OBJEXTG)
p8_part1part21_part1part25part25_d86h2l121.mod: d86h2l121.$(OBJEXTG)
p8_part1part21_part1part25part25_d88h2l131.mod: d88h2l131.$(OBJEXTG)
p8_part1part21_part1part25part25_d88h2l132.mod: d88h2l132.$(OBJEXTG)
p8_part1part21_part1part25part25_d88h2l121.mod: d88h2l121.$(OBJEXTG)
p8_part1part21_part1part25part25_abbrevd11h2.mod: abbrevd11h2.$(OBJEXTG)
p8_part1part21_part1part25part25_d11h2l1.mod: d11h2l1.$(OBJEXTG)
p8_part1part21_part1part25part25_d11h2l1d.mod: d11h2l1d.$(OBJEXTG)
p8_part1part21_part1part25part25_abbrevd84h2.mod: abbrevd84h2.$(OBJEXTG)
p8_part1part21_part1part25part25_d84h2l1.mod: d84h2l1.$(OBJEXTG)
p8_part1part21_part1part25part25_d84h2l1d.mod: d84h2l1d.$(OBJEXTG)
p8_part1part21_part1part25part25_abbrevd86h2.mod: abbrevd86h2.$(OBJEXTG)
p8_part1part21_part1part25part25_d86h2l1.mod: d86h2l1.$(OBJEXTG)
p8_part1part21_part1part25part25_d86h2l1d.mod: d86h2l1d.$(OBJEXTG)
p8_part1part21_part1part25part25_abbrevd88h2.mod: abbrevd88h2.$(OBJEXTG)
p8_part1part21_part1part25part25_d88h2l1.mod: d88h2l1.$(OBJEXTG)
p8_part1part21_part1part25part25_d88h2l1d.mod: d88h2l1d.$(OBJEXTG)
p8_part1part21_part1part25part25_amplitudeh2.mod: amplitudeh2.$(OBJEXTG)
p8_part1part21_part1part25part25_globalsh2.mod: globals.$(OBJEXTG)
